In [2]:
import tensorflow as tf

In [3]:
# TF work as a graph computation model

graph1 = tf.Graph()

In [4]:
# now call TF functions that construct new tf.Operation &
# tf.Tensor objects and add them to the graph1

with graph1.as_default():
    a = tf.constant([2], name = 'constant_a')
    b = tf.constant([3], name = 'constant_b') 

In [8]:
# Printing the value of a

tf.compat.v1.disable_eager_execution() #and the other is

sess = tf.compat.v1.Session(graph = graph1)
result = sess.run(a)
print(result)
sess.close()

[2]


In [9]:
# Printing the value of a {CODE-NOT-WORKING}

# sess = tf.Session(graph = graph1)
# result = sess.run(a)
# print(result)
# sess.close()

In [10]:
with graph1.as_default():
    c = tf.add(a, b)

In [12]:
sess = tf.compat.v1.Session(graph = graph1)

In [22]:
with tf.compat.v1.Session(graph = graph1) as sess:
    result = sess.run(c)
    print(result)

[5]


In [23]:
# Defining multidimensional arrays using TensorFlow

In [28]:
graph2 = tf.Graph()
with graph2.as_default():
    Scalar = tf.constant(2)
    Vector = tf.constant([5,6,2])
    Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
    Tensor = tf.constant([ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ])
    
with tf.compat.v1.Session(graph = graph2) as sess:
    result = sess.run(Scalar)
    print ("Scalar (1 entry):\n %s \n" % result)
    result = sess.run(Vector)
    print ("Vector (3 entries) :\n %s \n" % result)
    result = sess.run(Matrix)
    print ("Matrix (3x3 entries):\n %s \n" % result)
    result = sess.run(Tensor)
    print ("Tensor (3x3x3 entries) :\n %s \n" % result)

Scalar (1 entry):
 2 

Vector (3 entries) :
 [5 6 2] 

Matrix (3x3 entries):
 [[1 2 3]
 [2 3 4]
 [3 4 5]] 

Tensor (3x3x3 entries) :
 [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]] 



In [30]:
Scalar.shape

TensorShape([])

In [31]:
Tensor.shape

TensorShape([3, 3, 3])

In [35]:
# adding 2 matrixs using TF & normal function

graph3 = tf.Graph()
with graph3.as_default():
    Matrix_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
    Matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])

    add_1_operation = tf.add(Matrix_one, Matrix_two)
    add_2_operation = Matrix_one + Matrix_two

with tf.compat.v1.Session(graph =graph3) as sess:
    result = sess.run(add_1_operation)
    print ("Defined using tensorflow function :")
    print(result)
    result = sess.run(add_2_operation)
    print ("Defined using normal expressions :")
    print(result)

Defined using tensorflow function :
[[3 4 5]
 [4 5 6]
 [5 6 7]]
Defined using normal expressions :
[[3 4 5]
 [4 5 6]
 [5 6 7]]


In [39]:
#  multipication of 2 matrix using TF

graph4 = tf.Graph()
with graph4.as_default():
    Matrix_one = tf.constant([[2,3],[3,4]])
    Matrix_two = tf.constant([[2,3],[3,4]])

    mul_operation = tf.matmul(Matrix_one, Matrix_two)

with tf.compat.v1.Session(graph = graph4) as sess:
    result = sess.run(mul_operation)
    print ("Defined using tensorflow function :")
    print(result)

Defined using tensorflow function :
[[13 18]
 [18 25]]


In [40]:
v = tf.Variable(0)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [46]:
update = tf.compat.v1.assign(v, v+1)

In [48]:
init_op = tf.compat.v1.global_variables_initializer()

In [50]:
with tf.compat.v1.Session() as session:
    session.run(init_op)
    print(session.run(v))
    for _ in range(3):
        session.run(update)
        print(session.run(v))

0
1
2
3


In [51]:
 #PLACEHOLDER

In [54]:
a = tf.compat.v1.placeholder(tf.float32)

In [55]:
b = a*2

In [56]:
with tf.compat.v1.Session() as sess:
    result = sess.run(b, feed_dict = {a:3.5})
    print(result)

7.0


In [58]:
dictionary={a: [ [ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ] , [ [13,14,15],[16,17,18],[19,20,21],[22,23,24] ] ] }

with tf.compat.v1.Session() as sess:
    result = sess.run(b,feed_dict=dictionary)
    print (result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


In [59]:
# Operations are nodes that represent the mathematical operations 
# over the tensors on a graph. These operations can be any kind 
# of functions, like add and subtract tensor or maybe an activation function.

# tf.constant, tf.matmul, tf.add, tf.nn.sigmoid
# are some of the operations in TensorFlow
# (tf.nn.sigmoid is an activation function)

In [61]:
graph5 = tf.Graph()
with graph5.as_default():
    a = tf.constant([5])
    b = tf.constant([2])
    c = tf.add(a,b)
    d = tf.subtract(a,b)

with tf.compat.v1.Session(graph = graph5) as sess:
    result = sess.run(c)
    print ('c =: %s' % result)
    result = sess.run(d)
    print ('d =: %s' % result)

c =: [7]
d =: [3]
